language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 185.8.165.64
deploy:
  provider: script
  script: rsync -r --delete-after --delete --quiet /tmp/.env travis@185.8.165.64:/home/travis/projects/kindergarten-api/current
before_install:
- echo $TRAVIS_BUILD_DIR
- openssl aes-256-cbc -K $encrypted_0e37d283556b_key -iv $encrypted_0e37d283556b_iv
  -in .env.enc -out /tmp/.env -d
- openssl aes-256-cbc -K $encrypted_0e37d283556b_key -iv $encrypted_0e37d283556b_iv
  -in travis_pm2_rsa.enc -out /tmp/travis_pm2_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis_pm2_rsa
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add /tmp/travis_pm2_rsa
after_success:
- npm install pm2 -g
- pm2 deploy ecosystem.config.js production update
- pm2 deploy ecosystem.config.js production exec "pm2 reload all"
